server:
  servlet:
    contextPath: /amq-demo
  port: 0

spring:
  application:
    name: amq-demo
app:
  reload:
    time: -120
activemq:
  username: master
  password: password
  broker:
    url: tcp://localhost:61616